List restaurants = [
  {
    "img": "assets/images/food1.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "0",
    "rewards": "Two points far from a reward",
    "col": "green",
  },
  {
    "img": "assets/images/food2.jpeg",
    "title": "Uncle Boons",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "1",
    "rewards": "Five points far from a reward",
    "col": "blue",
  },
  {
    "img": "assets/images/food3.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "2",
    "rewards": "Three points far from a reward",
    "col": "red",
  },
  {
    "img": "assets/images/food4.jpeg",
    "title": "Uncle Boons",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "3",
    "rewards": "Two points far from a reward",
    "col": "cyan",
  },
  {
    "img": "assets/images/food5.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "4",
    "rewards": "Two points far from a reward",
    "col": "violet",
  },
  {
    "img": "assets/images/food6.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "5",
    "rewards": "Two points far from a reward",
    "col": "yellow",
  },
  {
    "img": "assets/images/food7.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "6",
    "rewards": "Two points far from a reward",
    "col": "orange",
  },
  {
    "img": "assets/images/food8.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "7",
    "rewards": "Two points far from a reward",
    "col": "green",
  },
  {
    "img": "assets/images/food9.jpeg",
    "title": "Happy Jones",
    "address": "1278 Loving Acres RoadKansas City, MO 64110",
    "rating": "8",
    "rewards": "Two points far from a reward",
    "col": "blue",
  }
];
